replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: #TODO repository where our custom image has been pushed
  tag: 1.0.0
  pullPolicy: IfNotPresent 
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
  readinessProbe:
    httpGet:
      path: /ready
      port: 3000
    initialDelaySeconds: 3
    periodSeconds: 5
  livenessProbe:
    httpGet:
      path: /live
      port: 3000
    initialDelaySeconds: 40
    periodSeconds: 10  
service:
  name: Node
  type: NodePort
  servicePort: 3000 #TODO put custom port here

